// ============================================================
// Diccionario.js — Mapeo de vocabulario EN↔ES
// Responsable: Mijeli
// Compilador Traductor Inglés-Español 2026
// ============================================================

// ─── INGLÉS → ESPAÑOL ─────────────────────────────────────────
export const EN_ES = {
    // Artículos
    'the': 'el', 'a': 'un', 'an': 'un',

    // Pronombres personales
    'i': 'yo', 'you': 'tú', 'he': 'él', 'she': 'ella',
    'it': 'ello', 'we': 'nosotros', 'they': 'ellos',
    'me': 'me', 'him': 'le', 'her': 'le', 'us': 'nos', 'them': 'les',

    // Posesivos
    'my': 'mi', 'your': 'tu', 'his': 'su', 'its': 'su',
    'our': 'nuestro', 'their': 'su',

    // Verbos auxiliares
    'is': 'es', 'are': 'son', 'was': 'era', 'were': 'eran',
    'am': 'soy', 'be': 'ser', 'been': 'sido', 'being': 'siendo',
    'do': 'hacer', 'does': 'hace', 'did': 'hizo',
    'have': 'tener', 'has': 'tiene', 'had': 'tenía',
    'will': 'va a', 'would': 'haría', 'shall': 'deberá',
    'should': 'debería', 'can': 'puede', 'could': 'podría',
    'may': 'puede', 'might': 'podría', 'must': 'debe',

    // Verbos comunes
    'run': 'correr', 'runs': 'corre', 'ran': 'corrió',
    'eat': 'comer', 'eats': 'come', 'ate': 'comió',
    'sleep': 'dormir', 'sleeps': 'duerme', 'slept': 'durmió',
    'study': 'estudiar', 'studies': 'estudia', 'studied': 'estudió',
    'learn': 'aprender', 'learns': 'aprende', 'learned': 'aprendió',
    'work': 'trabajar', 'works': 'trabaja', 'worked': 'trabajó',
    'walk': 'caminar', 'walks': 'camina', 'walked': 'caminó',
    'talk': 'hablar', 'talks': 'habla', 'talked': 'habló',
    'speak': 'hablar', 'speaks': 'habla', 'spoke': 'habló',
    'write': 'escribir', 'writes': 'escribe', 'wrote': 'escribió',
    'read': 'leer', 'reads': 'lee',
    'see': 'ver', 'sees': 've', 'saw': 'vio',
    'look': 'mirar', 'looks': 'mira', 'looked': 'miró',
    'come': 'venir', 'comes': 'viene', 'came': 'vino',
    'go': 'ir', 'goes': 'va', 'went': 'fue',
    'know': 'saber', 'knows': 'sabe', 'knew': 'supo',
    'think': 'pensar', 'thinks': 'piensa', 'thought': 'pensó',
    'want': 'querer', 'wants': 'quiere', 'wanted': 'quiso',
    'need': 'necesitar', 'needs': 'necesita', 'needed': 'necesitó',
    'love': 'amar', 'loves': 'ama', 'loved': 'amó',
    'like': 'gustar', 'likes': 'gusta', 'liked': 'gustó',
    'help': 'ayudar', 'helps': 'ayuda', 'helped': 'ayudó',
    'support': 'apoyar', 'supports': 'apoya', 'supported': 'apoyó',
    'encourage': 'animar', 'encourages': 'anima', 'encouraged': 'animó',
    'believe': 'creer', 'believes': 'cree', 'believed': 'creyó',
    'give': 'dar', 'gives': 'da', 'gave': 'dio',
    'take': 'tomar', 'takes': 'toma', 'took': 'tomó',
    'make': 'hacer', 'makes': 'hace', 'made': 'hizo',
    'find': 'encontrar', 'finds': 'encuentra', 'found': 'encontró',
    'tell': 'decir', 'tells': 'dice', 'told': 'dijo',
    'ask': 'preguntar', 'asks': 'pregunta', 'asked': 'preguntó',
    'try': 'intentar', 'tries': 'intenta', 'tried': 'intentó',
    'use': 'usar', 'uses': 'usa', 'used': 'usó',
    'feel': 'sentir', 'feels': 'siente', 'felt': 'sintió',
    'become': 'convertirse', 'becomes': 'se convierte', 'became': 'se convirtió',
    'show': 'mostrar', 'shows': 'muestra', 'showed': 'mostró',
    'leave': 'salir', 'leaves': 'sale', 'left': 'salió',
    'bring': 'traer', 'brings': 'trae', 'brought': 'trajo',
    'begin': 'comenzar', 'begins': 'comienza', 'began': 'comenzó',
    'keep': 'mantener', 'keeps': 'mantiene', 'kept': 'mantuvo',
    'start': 'empezar', 'starts': 'empieza', 'started': 'empezó',
    'change': 'cambiar', 'changes': 'cambia', 'changed': 'cambió',
    'play': 'jugar', 'plays': 'juega', 'played': 'jugó',
    'move': 'mover', 'moves': 'mueve', 'moved': 'movió',
    'live': 'vivir', 'lives': 'vive', 'lived': 'vivió',
    'happen': 'pasar', 'happens': 'pasa', 'happened': 'pasó',
    'call': 'llamar', 'calls': 'llama', 'called': 'llamó',
    'lose': 'perder', 'loses': 'pierde', 'lost': 'perdió',
    'waste': 'desperdiciar', 'wastes': 'desperdicia', 'wasted': 'desperdició',
    'dream': 'soñar', 'dreams': 'sueña', 'dreamed': 'soñó',
    'wake': 'despertar', 'wakes': 'despierta', 'woke': 'despertó',
    'drink': 'beber', 'drinks': 'bebe', 'drank': 'bebió',
    'swim': 'nadar', 'swims': 'nada', 'swam': 'nadó',
    'drive': 'manejar', 'drives': 'maneja', 'drove': 'manejó',
    'fly': 'volar', 'flies': 'vuela', 'flew': 'voló',
    'sing': 'cantar', 'sings': 'canta', 'sang': 'cantó',
    'dance': 'bailar', 'dances': 'baila', 'danced': 'bailó',
    'draw': 'dibujar', 'draws': 'dibuja', 'drew': 'dibujó',
    'buy': 'comprar', 'buys': 'compra', 'bought': 'compró',
    'sell': 'vender', 'sells': 'vende', 'sold': 'vendió',
    'pay': 'pagar', 'pays': 'paga', 'paid': 'pagó',
    'open': 'abrir', 'opens': 'abre', 'opened': 'abrió',
    'close': 'cerrar', 'closes': 'cierra', 'closed': 'cerró',
    'send': 'enviar', 'sends': 'envía', 'sent': 'envió',
    'receive': 'recibir', 'receives': 'recibe', 'received': 'recibió',
    'wait': 'esperar', 'waits': 'espera', 'waited': 'esperó',
    'stop': 'parar', 'stops': 'para', 'stopped': 'paró',
    'spend': 'gastar', 'spends': 'gasta', 'spent': 'gastó',
    'win': 'ganar', 'wins': 'gana', 'won': 'ganó',
    'meet': 'conocer', 'meets': 'conoce', 'met': 'conoció',
    'follow': 'seguir', 'follows': 'sigue', 'followed': 'siguió',
    'remember': 'recordar', 'remembers': 'recuerda', 'remembered': 'recordó',
    'understand': 'entender', 'understands': 'entiende', 'understood': 'entendió',
    'stand': 'estar de pie', 'stands': 'está de pie', 'stood': 'estuvo de pie',
    'sit': 'sentarse', 'sits': 'se sienta', 'sat': 'se sentó',
    'put': 'poner', 'puts': 'pone',
    'let': 'dejar', 'lets': 'deja',
    'set': 'establecer', 'sets': 'establece',
    'get': 'obtener', 'gets': 'obtiene', 'got': 'obtuvo',
    'cut': 'cortar', 'cuts': 'corta',
    'hit': 'golpear', 'hits': 'golpea',
    'hold': 'sostener', 'holds': 'sostiene', 'held': 'sostuvo',
    'turn': 'girar', 'turns': 'gira', 'turned': 'giró',
    'grow': 'crecer', 'grows': 'crece', 'grew': 'creció',
    'fall': 'caer', 'falls': 'cae', 'fell': 'cayó',
    'pass': 'pasar', 'passes': 'pasa', 'passed': 'pasó',
    'include': 'incluir', 'includes': 'incluye', 'included': 'incluyó',

    // Sustantivos comunes
    'cat': 'gato', 'cats': 'gatos',
    'dog': 'perro', 'dogs': 'perros',
    'student': 'estudiante', 'students': 'estudiantes',
    'teacher': 'maestro', 'teachers': 'maestros',
    'parent': 'padre', 'parents': 'padres',
    'doctor': 'médico', 'doctors': 'médicos',
    'house': 'casa', 'houses': 'casas',
    'school': 'escuela', 'schools': 'escuelas',
    'book': 'libro', 'books': 'libros',
    'day': 'día', 'days': 'días',
    'time': 'tiempo',
    'year': 'año', 'years': 'años',
    'life': 'vida',
    'world': 'mundo',
    'man': 'hombre', 'men': 'hombres',
    'woman': 'mujer', 'women': 'mujeres',
    'child': 'niño', 'children': 'niños',
    'boy': 'niño', 'boys': 'niños',
    'girl': 'niña', 'girls': 'niñas',
    'friend': 'amigo', 'friends': 'amigos',
    'family': 'familia',
    'home': 'hogar',
    'city': 'ciudad', 'cities': 'ciudades',
    'country': 'país',
    'food': 'comida',
    'water': 'agua',
    'money': 'dinero',
    'job': 'trabajo', 'jobs': 'trabajos',
    'hand': 'mano', 'hands': 'manos',
    'head': 'cabeza', 'heads': 'cabezas',
    'eye': 'ojo', 'eyes': 'ojos',
    'heart': 'corazón', 'hearts': 'corazones',
    'mind': 'mente',
    'body': 'cuerpo', 'bodies': 'cuerpos',
    'voice': 'voz', 'voices': 'voces',
    'word': 'palabra', 'words': 'palabras',
    'place': 'lugar', 'places': 'lugares',
    'way': 'camino', 'ways': 'caminos',
    'thing': 'cosa', 'things': 'cosas',
    'problem': 'problema', 'problems': 'problemas',
    'question': 'pregunta', 'questions': 'preguntas',
    'answer': 'respuesta', 'answers': 'respuestas',
    'idea': 'idea', 'ideas': 'ideas',
    'future': 'futuro',
    'career': 'carrera', 'careers': 'carreras',
    'garden': 'jardín', 'gardens': 'jardines',
    'morning': 'mañana',
    'night': 'noche',
    'coffee': 'café',
    'cup': 'taza', 'cups': 'tazas',
    'table': 'mesa', 'tables': 'mesas',
    'chair': 'silla', 'chairs': 'sillas',
    'door': 'puerta', 'doors': 'puertas',
    'window': 'ventana', 'windows': 'ventanas',
    'car': 'carro', 'cars': 'carros',
    'road': 'camino', 'roads': 'caminos',
    'river': 'río', 'rivers': 'ríos',
    'mountain': 'montaña', 'mountains': 'montañas',
    'music': 'música',
    'song': 'canción', 'songs': 'canciones',
    'game': 'juego', 'games': 'juegos',
    'sport': 'deporte', 'sports': 'deportes',
    'letter': 'carta', 'letters': 'cartas',
    'message': 'mensaje', 'messages': 'mensajes',
    'sentence': 'oración', 'sentences': 'oraciones',
    // Agregar en EN_ES, sección sustantivos:
    'apple': 'manzana', 'apples': 'manzanas',
    'orange': 'naranja', 'oranges': 'naranjas',
    'banana': 'plátano', 'bananas': 'plátanos',
    'grape': 'uva', 'grapes': 'uvas',
    'strawberry': 'fresa', 'strawberries': 'fresas',
    'tomato': 'tomate', 'tomatoes': 'tomates',
    'potato': 'papa', 'potatoes': 'papas',
    'bread': 'pan',
    'milk': 'leche',
    'egg': 'huevo', 'eggs': 'huevos',
    'cheese': 'queso',
    'meat': 'carne',
    'fish': 'pescado',
    'rice': 'arroz',
    'sugar': 'azúcar',
    'salt': 'sal',
    'oil': 'aceite',
    'flower': 'flor', 'flowers': 'flores',
    'tree': 'árbol', 'trees': 'árboles',
    'sun': 'sol',
    'moon': 'luna',
    'star': 'estrella', 'stars': 'estrellas',
    'sky': 'cielo',
    'rain': 'lluvia',
    'wind': 'viento',
    'snow': 'nieve',
    'fire': 'fuego',
    'earth': 'tierra',
    'air': 'aire',
    'sea': 'mar',
    'beach': 'playa',
    'forest': 'bosque',
    'animal': 'animal', 'animals': 'animales',
    'bird': 'pájaro', 'birds': 'pájaros',
    'horse': 'caballo', 'horses': 'caballos',
    'cow': 'vaca', 'cows': 'vacas',
    'pig': 'cerdo', 'pigs': 'cerdos',
    'color': 'color', 'colors': 'colores',
    'red': 'rojo', 'blue': 'azul', 'green': 'verde',
    'yellow': 'amarillo', 'white': 'blanco', 'black': 'negro',
    'pink': 'rosado', 'purple': 'morado', 'brown': 'café',
    'number': 'número', 'numbers': 'números',
    'name': 'nombre', 'names': 'nombres',
    'age': 'edad',
    'size': 'tamaño',
    'price': 'precio', 'prices': 'precios',
    'hour': 'hora', 'hours': 'horas',
    'minute': 'minuto', 'minutes': 'minutos',
    'second': 'segundo', 'seconds': 'segundos',
    'week': 'semana', 'weeks': 'semanas',
    'month': 'mes', 'months': 'meses',
    'summer': 'verano', 'winter': 'invierno',
    'spring': 'primavera',
    'monday': 'lunes', 'tuesday': 'martes',
    'wednesday': 'miércoles', 'thursday': 'jueves',
    'friday': 'viernes', 'saturday': 'sábado', 'sunday': 'domingo',

    // Adjetivos comunes
    'good': 'bueno', 'bad': 'malo', 'big': 'grande', 'small': 'pequeño',
    'old': 'viejo', 'new': 'nuevo', 'young': 'joven',
    'happy': 'feliz', 'sad': 'triste', 'angry': 'enojado',
    'fast': 'rápido', 'slow': 'lento', 'hard': 'difícil',
    'easy': 'fácil', 'difficult': 'difícil', 'beautiful': 'hermoso',
    'ugly': 'feo', 'strong': 'fuerte', 'weak': 'débil',
    'long': 'largo', 'short': 'corto', 'tall': 'alto', 'high': 'alto',
    'low': 'bajo', 'hot': 'caliente', 'cold': 'frío',
    'warm': 'tibio', 'cool': 'fresco', 'clean': 'limpio',
    'dirty': 'sucio', 'rich': 'rico', 'poor': 'pobre',
    'right': 'correcto', 'wrong': 'incorrecto', 'true': 'verdadero',
    'false': 'falso', 'important': 'importante', 'different': 'diferente',
    'same': 'mismo', 'great': 'genial', 'little': 'pequeño',
    'own': 'propio', 'last': 'último', 'next': 'siguiente',
    'early': 'temprano', 'late': 'tarde', 'free': 'libre',
    'full': 'lleno', 'sure': 'seguro', 'ready': 'listo',
    'real': 'real', 'special': 'especial', 'famous': 'famoso',
    'possible': 'posible', 'necessary': 'necesario',

    // Adverbios
    'very': 'muy', 'too': 'también', 'also': 'también',
    'always': 'siempre', 'never': 'nunca', 'often': 'a menudo',
    'sometimes': 'a veces', 'usually': 'usualmente',
    'here': 'aquí', 'there': 'allí', 'now': 'ahora',
    'then': 'entonces', 'today': 'hoy', 'yesterday': 'ayer',
    'tomorrow': 'mañana', 'soon': 'pronto', 'already': 'ya',
    'still': 'todavía', 'again': 'de nuevo',
    'together': 'juntos', 'alone': 'solo',
    'well': 'bien', 'badly': 'mal',
    'quickly': 'rápidamente', 'slowly': 'lentamente',
    'every': 'cada', 'much': 'mucho', 'many': 'muchos',
    'more': 'más', 'most': 'más', 'less': 'menos',
    'just': 'solo', 'only': 'solo', 'even': 'incluso',
    'almost': 'casi', 'really': 'realmente',

    // Preposiciones
    'in': 'en', 'on': 'en', 'at': 'en', 'to': 'a',
    'for': 'para', 'with': 'con', 'from': 'de', 'of': 'de',
    'about': 'sobre', 'by': 'por', 'up': 'arriba', 'down': 'abajo',
    'out': 'fuera', 'over': 'sobre', 'under': 'bajo',
    'between': 'entre', 'through': 'a través',
    'after': 'después', 'before': 'antes',
    'during': 'durante', 'since': 'desde',
    'without': 'sin', 'within': 'dentro', 'against': 'contra',
    'into': 'dentro de', 'off': 'fuera de',

    // Conjunciones
    'and': 'y', 'but': 'pero', 'or': 'o', 'if': 'si',
    'because': 'porque', 'although': 'aunque', 'while': 'mientras',
    'when': 'cuando', 'unless': 'a menos que',
    'until': 'hasta que', 'that': 'que', 'so': 'así que',
    'yet': 'sin embargo', 'nor': 'ni',

    // Negación
    'not': 'no', "n't": 'no', 'no': 'no',

    // Interrogativos
    'what': 'qué', 'who': 'quién', 'where': 'dónde',
    'why': 'por qué', 'how': 'cómo', 'which': 'cuál',

    // Números
    'one': 'uno', 'two': 'dos', 'three': 'tres', 'four': 'cuatro',
    'five': 'cinco', 'six': 'seis', 'seven': 'siete', 'eight': 'ocho',
    'nine': 'nueve', 'ten': 'diez', 'hundred': 'cien', 'thousand': 'mil',
};

// ─── ESPAÑOL → INGLÉS ─────────────────────────────────────────
export const ES_EN = {
    // Artículos
    'el': 'the', 'la': 'the', 'los': 'the', 'las': 'the',
    'un': 'a', 'una': 'a', 'unos': 'some', 'unas': 'some',

    // Pronombres
    'yo': 'I', 'tú': 'you', 'él': 'he', 'ella': 'she',
    'nosotros': 'we', 'ellos': 'they', 'ellas': 'they',
    'me': 'me', 'te': 'you', 'se': 'himself',
    'nos': 'us', 'les': 'them', 'lo': 'it', 'le': 'him',

    // Posesivos
    'mi': 'my', 'mis': 'my', 'tu': 'your', 'tus': 'your',
    'su': 'his', 'sus': 'his', 'nuestro': 'our', 'nuestra': 'our',

    // Verbos auxiliares
    'es': 'is', 'son': 'are', 'era': 'was', 'eran': 'were',
    'soy': 'am', 'somos': 'are', 'eres': 'are',
    'ser': 'be', 'sido': 'been', 'siendo': 'being',
    'estoy': 'am', 'estás': 'are', 'está': 'is',
    'estamos': 'are', 'están': 'are',
    'he': 'have', 'has': 'have', 'ha': 'has',
    'hemos': 'have', 'han': 'have',

    // Verbos comunes
    'correr': 'run', 'corre': 'runs', 'corrió': 'ran',
    'comer': 'eat', 'come': 'eats', 'comió': 'ate',
    'dormir': 'sleep', 'duerme': 'sleeps', 'durmió': 'slept',
    'estudiar': 'study', 'estudia': 'studies', 'estudió': 'studied',
    'aprender': 'learn', 'aprende': 'learns', 'aprendió': 'learned',
    'trabajar': 'work', 'trabaja': 'works', 'trabajó': 'worked',
    'caminar': 'walk', 'camina': 'walks', 'caminó': 'walked',
    'hablar': 'speak', 'habla': 'speaks', 'habló': 'spoke',
    'escribir': 'write', 'escribe': 'writes', 'escribió': 'wrote',
    'leer': 'read', 'lee': 'reads',
    'ver': 'see', 've': 'sees', 'vio': 'saw',
    'mirar': 'look', 'mira': 'looks', 'miró': 'looked',
    'venir': 'come', 'viene': 'comes', 'vino': 'came',
    'ir': 'go', 'va': 'goes', 'fue': 'went',
    'saber': 'know', 'sabe': 'knows', 'supo': 'knew',
    'pensar': 'think', 'piensa': 'thinks', 'pensó': 'thought',
    'querer': 'want', 'quiere': 'wants', 'quiso': 'wanted',
    'necesitar': 'need', 'necesita': 'needs', 'necesitó': 'needed',
    'amar': 'love', 'ama': 'loves', 'amó': 'loved',
    'gustar': 'like', 'gusta': 'likes', 'gustó': 'liked',
    'ayudar': 'help', 'ayuda': 'helps', 'ayudó': 'helped',
    'apoyar': 'support', 'apoya': 'supports', 'apoyó': 'supported',
    'animar': 'encourage', 'anima': 'encourages', 'animó': 'encouraged',
    'creer': 'believe', 'cree': 'believes', 'creyó': 'believed',
    'dar': 'give', 'da': 'gives', 'dio': 'gave',
    'tomar': 'take', 'toma': 'takes', 'tomó': 'took',
    'hacer': 'make', 'hace': 'makes', 'hizo': 'made',
    'encontrar': 'find', 'encuentra': 'finds', 'encontró': 'found',
    'decir': 'say', 'dice': 'says', 'dijo': 'said',
    'preguntar': 'ask', 'pregunta': 'asks', 'preguntó': 'asked',
    'intentar': 'try', 'intenta': 'tries', 'intentó': 'tried',
    'usar': 'use', 'usa': 'uses', 'usó': 'used',
    'sentir': 'feel', 'siente': 'feels', 'sintió': 'felt',
    'mostrar': 'show', 'muestra': 'shows', 'mostró': 'showed',
    'perder': 'lose', 'pierde': 'loses', 'perdió': 'lost',
    'desperdiciar': 'waste', 'desperdicia': 'wastes', 'desperdició': 'wasted',
    'despertar': 'wake', 'despierta': 'wakes', 'despertó': 'woke',
    'beber': 'drink', 'bebe': 'drinks', 'bebió': 'drank',
    'nadar': 'swim', 'nada': 'swims', 'nadó': 'swam',
    'manejar': 'drive', 'maneja': 'drives', 'manejó': 'drove',
    'cantar': 'sing', 'canta': 'sings', 'cantó': 'sang',
    'bailar': 'dance', 'baila': 'dances', 'bailó': 'danced',
    'comprar': 'buy', 'compra': 'buys', 'compró': 'bought',
    'vender': 'sell', 'vende': 'sells', 'vendió': 'sold',
    'pagar': 'pay', 'paga': 'pays', 'pagó': 'paid',
    'abrir': 'open', 'abre': 'opens', 'abrió': 'opened',
    'cerrar': 'close', 'cierra': 'closes', 'cerró': 'closed',
    'esperar': 'wait', 'espera': 'waits', 'esperó': 'waited',
    'ganar': 'win', 'gana': 'wins', 'ganó': 'won',
    'seguir': 'follow', 'sigue': 'follows', 'siguió': 'followed',
    'recordar': 'remember', 'recuerda': 'remembers', 'recordó': 'remembered',
    'entender': 'understand', 'entiende': 'understands', 'entendió': 'understood',
    'empezar': 'start', 'empieza': 'starts', 'empezó': 'started',
    'terminar': 'finish', 'termina': 'finishes', 'terminó': 'finished',
    'cambiar': 'change', 'cambia': 'changes', 'cambió': 'changed',
    'vivir': 'live', 'vive': 'lives', 'vivió': 'lived',
    'crecer': 'grow', 'crece': 'grows', 'creció': 'grew',
    'caer': 'fall', 'cae': 'falls', 'cayó': 'fell',
    'conocer': 'meet', 'conoce': 'meets', 'conoció': 'met',
    'soñar': 'dream', 'sueña': 'dreams', 'soñó': 'dreamed',
    'jugar': 'play', 'juega': 'plays', 'jugó': 'played',
    'llevar': 'carry', 'lleva': 'carries', 'llevó': 'carried',
    'llamar': 'call', 'llama': 'calls', 'llamó': 'called',
    'llegar': 'arrive', 'llega': 'arrives', 'llegó': 'arrived',
    'pasar': 'pass', 'pasa': 'passes', 'pasó': 'passed',

    // Sustantivos
    'gato': 'cat', 'gatos': 'cats',
    'perro': 'dog', 'perros': 'dogs',
    'estudiante': 'student', 'estudiantes': 'students',
    'maestro': 'teacher', 'maestros': 'teachers',
    'padre': 'father', 'padres': 'parents',
    'médico': 'doctor', 'médicos': 'doctors',
    'médica': 'doctor',
    'casa': 'house', 'casas': 'houses',
    'escuela': 'school', 'escuelas': 'schools',
    'libro': 'book', 'libros': 'books',
    'día': 'day', 'días': 'days',
    'tiempo': 'time',
    'año': 'year', 'años': 'years',
    'vida': 'life',
    'mundo': 'world',
    'hombre': 'man', 'hombres': 'men',
    'mujer': 'woman', 'mujeres': 'women',
    'niño': 'boy', 'niños': 'boys',
    'niña': 'girl', 'niñas': 'girls',
    'amigo': 'friend', 'amigos': 'friends',
    'familia': 'family',
    'hogar': 'home',
    'ciudad': 'city', 'ciudades': 'cities',
    'país': 'country',
    'comida': 'food',
    'agua': 'water',
    'dinero': 'money',
    'trabajo': 'work',
    'mano': 'hand', 'manos': 'hands',
    'cabeza': 'head', 'cabezas': 'heads',
    'ojo': 'eye', 'ojos': 'eyes',
    'corazón': 'heart', 'corazones': 'hearts',
    'mente': 'mind',
    'cuerpo': 'body', 'cuerpos': 'bodies',
    'voz': 'voice', 'voces': 'voices',
    'palabra': 'word', 'palabras': 'words',
    'lugar': 'place', 'lugares': 'places',
    'cosa': 'thing', 'cosas': 'things',
    'problema': 'problem', 'problemas': 'problems',
    'preguntas': 'questions',
    'respuesta': 'answer', 'respuestas': 'answers',
    'idea': 'idea', 'ideas': 'ideas',
    'sueño': 'dream', 'sueños': 'dreams',
    'futuro': 'future',
    'carrera': 'career', 'carreras': 'careers',
    'jardín': 'garden', 'jardines': 'gardens',
    'noche': 'night',
    'café': 'coffee',
    'taza': 'cup', 'tazas': 'cups',
    'mesa': 'table', 'mesas': 'tables',
    'silla': 'chair', 'sillas': 'chairs',
    'puerta': 'door', 'puertas': 'doors',
    'ventana': 'window', 'ventanas': 'windows',
    'carro': 'car', 'carros': 'cars',
    'camino': 'road', 'caminos': 'roads',
    'río': 'river', 'ríos': 'rivers',
    'montaña': 'mountain', 'montañas': 'mountains',
    'música': 'music',
    'canción': 'song', 'canciones': 'songs',
    'juego': 'game', 'juegos': 'games',
    'deporte': 'sport', 'deportes': 'sports',
    'carta': 'letter', 'cartas': 'letters',
    'mensaje': 'message', 'mensajes': 'messages',

    // Adjetivos
    'bueno': 'good', 'malo': 'bad', 'grande': 'big', 'pequeño': 'small',
    'viejo': 'old', 'nuevo': 'new', 'joven': 'young',
    'feliz': 'happy', 'triste': 'sad', 'enojado': 'angry',
    'rápido': 'fast', 'lento': 'slow', 'difícil': 'difficult',
    'fácil': 'easy', 'hermoso': 'beautiful', 'bonito': 'pretty',
    'feo': 'ugly', 'fuerte': 'strong', 'débil': 'weak',
    'largo': 'long', 'corto': 'short', 'alto': 'tall',
    'bajo': 'low', 'caliente': 'hot', 'frío': 'cold',
    'tibio': 'warm', 'fresco': 'cool', 'limpio': 'clean',
    'sucio': 'dirty', 'rico': 'rich', 'pobre': 'poor',
    'correcto': 'right', 'incorrecto': 'wrong',
    'verdadero': 'true', 'falso': 'false',
    'importante': 'important', 'diferente': 'different',
    'mismo': 'same', 'propio': 'own', 'último': 'last',
    'siguiente': 'next', 'libre': 'free', 'lleno': 'full',
    'seguro': 'sure', 'listo': 'ready', 'real': 'real',
    'especial': 'special', 'famoso': 'famous',
    'posible': 'possible', 'necesario': 'necessary',
    'hermosa': 'beautiful', 'bonita': 'pretty',

    // Adverbios
    'muy': 'very', 'también': 'also',
    'nunca': 'never', 'a menudo': 'often', 'a veces': 'sometimes',
    'aquí': 'here', 'allí': 'there', 'ahora': 'now',
    'entonces': 'then', 'hoy': 'today', 'ayer': 'yesterday',
    'pronto': 'soon', 'ya': 'already',
    'todavía': 'still', 'juntos': 'together',
    'solo': 'alone', 'bien': 'well', 'mal': 'badly',
    'rápidamente': 'quickly', 'lentamente': 'slowly',
    'cada': 'every', 'mucho': 'much', 'muchos': 'many',
    'más': 'more', 'menos': 'less', 'casi': 'almost',
    'realmente': 'really', 'tan': 'so', 'tanto': 'so much',
    'siempre': 'always', 'después': 'after', 'antes': 'before',

    // Preposiciones
    'en': 'in', 'a': 'to', 'de': 'of', 'para': 'for',
    'con': 'with', 'por': 'by', 'sin': 'without',
    'sobre': 'about', 'entre': 'between',
    'durante': 'during', 'desde': 'since',
    'hacia': 'toward', 'hasta': 'until', 'contra': 'against',
    'dentro': 'inside', 'fuera': 'outside',
    'arriba': 'up', 'abajo': 'down',

    // Conjunciones
    'y': 'and', 'pero': 'but', 'o': 'or', 'si': 'if',
    'porque': 'because', 'aunque': 'although', 'mientras': 'while',
    'cuando': 'when', 'que': 'that', 'ni': 'nor',

    // Negación
    'no': 'not',

    // Interrogativos
    'qué': 'what', 'quién': 'who', 'dónde': 'where',
    'cuándo': 'when', 'cómo': 'how', 'cuál': 'which',

    // Números
    'uno': 'one', 'dos': 'two', 'tres': 'three', 'cuatro': 'four',
    'cinco': 'five', 'seis': 'six', 'siete': 'seven', 'ocho': 'eight',
    'nueve': 'nine', 'diez': 'ten', 'cien': 'hundred', 'mil': 'thousand',

    // Interjecciones
    'hola': 'hello', 'adiós': 'goodbye', 'gracias': 'thank you',
    'perdón': 'sorry', 'oye': 'hey', 'ay': 'oh',
};